export { default as GooseIcon} from "./goose.svg"
export { default as PhoneIcon } from "./profile/phone.png"
export { default as StarIcon } from "./profile/star.png"
export { default as SearchIcon } from "./searchbar/search.svg"
export { default as SearchIconDark } from "./searchbar/searchdark.svg"
export { default as SortIcon } from "./searchbar/sort.svg"
export { default as SelectedSortIcon } from "./searchbar/sort_select.svg"
export { default as ChevronLeftIcon } from "./chevron_left.png"
export { default as CrossIcon } from "./close.svg"
export { default as FlyingSaucerIcon } from "./flying-saucer.png"
export { default as MagnifierIcon } from "./magnifying-glass.svg"